# Standard Library
from enum import Enum


class ErrorCode(str, Enum):
    # APP
    CHALLENGE_FAILED = "CHALLENGE_FAILED"
    MISSING_RESOURCE = "MISSING_RESOURCE"

    # HTTP
    CONFLICT = "CONFLICT"
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST"
    INVALID_REQUEST = "INVALID_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    UNAUTHORIZED = "UNAUTHORIZED"
    UNKNOWN = "UNKNOWN"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"


class ErrorContextType(str, Enum):
    details = "details"
    help = "help"
