# Standard Library
from enum import Enum


class ErrorCode(str, Enum):
    CONFLICT = "CONFLICT"
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    MISSING_RESOURCE = "MISSING_RESOURCE"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    UNAUTHORIZED = "UNAUTHORIZED"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
