version: "3.8"

networks:
  server: # web_server
  cache: # redis
  database: # postgres
    driver: bridge

services:
  web_client:
    build:
      context: ./web_client
      dockerfile: Dockerfile.development
    container_name: casandra_client
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    entrypoint: "yarn dev -p $CLIENT_PORT"
    depends_on:
      - web_server
    networks:
      - server
    volumes:
      - "./web_client:${CLIENT_WORKDIR}"
      - "node_modules:${CLIENT_WORKDIR}/node_modules"
      - "nextjs_internals:${CLIENT_WORKDIR}/.next"
    environment:
      - APP_NAME=${APP_NAME} # the application name
      - PORT=${CLIENT_PORT} # Assign $CLIENT_PORT to $PORT env var in web_client

      # HTTP requests between host machine and server container will be done on this address
      - SERVER_BASE_URL=http://localhost:${PORT} # $PORT here is web_server container port

      # HTTP requests between client and server containers will be done on this address
      - SERVER_INTERNAL_ADDRESS=http://casandra_server:8000
    restart: unless-stopped

  web_server:
    build:
      context: ./web_services
      dockerfile: Dockerfile
    container_name: casandra_server
    expose:
      - 8000
    ports:
      - ${PORT}:8000
    command: "uvicorn app.main:app --log-level=debug --host='0.0.0.0' --port=8000 --reload"
    networks:
      - server
      - cache
      - database
    volumes:
      - "./web_services:${SERVER_WORKDIR}"
      - "virtual_env:${SERVER_WORKDIR}/.venv"
    depends_on:
      - redis
      - postgres
      - celery
    environment: &server_env
      - APP_NAME=${APP_NAME} # the application name
      - APP_DESC=${APP_DESC} # a short description of the application
      - CLIENT_HOSTS=${CLIENT_ADDRESSES} # List of hosts to whitelist for CORS
      - POSTGRES_HOST=casandra_services_postgres # the container name of the database container
      - POSTGRES_PORT=${POSTGRES_PORT} # the port on which to communicate with the database
      - POSTGRES_USER=${POSTGRES_USER} # the database user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # the database password
      - REDIS_URL=redis://casandra_services_cache:6379 # the name of the redis container as hostname
      - CELERY_BROKER_URL=redis://casandra_services_cache:6379
      - CELERY_RESULT_BACKEND=redis://casandra_services_cache:6379
    restart: unless-stopped

  celery:
    build:
      context: ./web_services
      dockerfile: Dockerfile
    container_name: casandra_celery
    command: >-
      watchfiles --filter python
      'celery -A app.core.worker.celery.celery --config app.celeryconfig worker --loglevel=info'
      ${SERVER_WORKDIR}/app/core/worker/
    networks:
      - server
      - cache
    volumes:
      - "./web_services:${SERVER_WORKDIR}"
      - "virtual_env:${SERVER_WORKDIR}/.venv"
    depends_on:
      - redis
    environment: *server_env
    restart: unless-stopped

  flower:
    image: mher/flower
    container_name: casandra_celery_flower
    ports:
      - 5556:5555
    command: celery flower --port=5555
    networks:
      - cache
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=redis://casandra_services_cache:6379
      - CELERY_RESULT_BACKEND=redis://casandra_services_cache:6379
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: casandra_services_cache
    expose:
      - 6379
    ports:
      - 6380:6379
    networks:
      - cache
    restart: unless-stopped

  postgres:
    container_name: casandra_services_postgres
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - database
    restart: unless-stopped

  pgadmin:
    container_name: casandra_services_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - database
    restart: unless-stopped

volumes:
  node_modules:
  nextjs_internals:
  postgres:
  pgadmin:
  virtual_env:
