events {}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;

    ''      close;
  }

  server {
    listen 80;
    server_name localhost;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certificates/dev_example_com.crt;
    ssl_certificate_key /etc/nginx/certificates/dev_example_com.key;

    # ssl_protocols  SSLv2 SSLv3 TLSv1;
    # ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
    ssl_prefer_server_ciphers on;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Client-Verify SUCCESS;
    proxy_set_header X-Client-DN $ssl_client_s_dn;
    proxy_set_header X-SSL-Subject $ssl_client_s_dn;
    proxy_set_header X-SSL-Issuer $ssl_client_i_dn;
    proxy_set_header X-Forwarded-Proto http;

    # For WebSocket support
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    location /api/v1/ {
      proxy_pass http://casandra_server:8000/;
    }

    # location /openapi.json {
    #   return 301 https://${host}/api/v1${request_uri};
    # }

    location / {
      proxy_pass http://casandra_client:3000/;
    }
  }
}
