/* tslint:disable */
/* eslint-disable */
/**
 * Kaybot
 * Kaybot is a chatbot that can be utilized for lead generation in the field of digital marketing.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
