FROM node:18-alpine

# Define working directory for client
WORKDIR /code

# Copy package metadata for client
COPY ./package.json .
COPY ./yarn.lock .

# Install dependencies
RUN yarn install --frozen-lockfile

