/* tslint:disable */
/* eslint-disable */
/**
 * Casandra
 * Casandra is a study assistant that consumes study materials, proposes and answers questions based on the provided materials.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * Account object representation with extra attributes to     foundational attributes
 * @export
 * @interface Account
 */
export interface Account {
  /**
   *
   * @type {string}
   * @memberof Account
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  updated_at: string;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  deleted_at: string | null;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  active_at: string;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  verified_at: string | null;
  /**
   *
   * @type {User}
   * @memberof Account
   */
  user: User | null;
}
/**
 * Attributes necessary for creating an Account object
 * @export
 * @interface AccountCreate
 */
export interface AccountCreate {
  /**
   *
   * @type {string}
   * @memberof AccountCreate
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof AccountCreate
   */
  password: string;
  /**
   *
   * @type {UserCreate}
   * @memberof AccountCreate
   */
  user: UserCreate;
}
/**
 *
 * @export
 * @interface ApplicationInfo
 */
export interface ApplicationInfo {
  /**
   *
   * @type {string}
   * @memberof ApplicationInfo
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationInfo
   */
  version: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationInfo
   */
  description: string;
}
/**
 * ChatMessage outbound attributes
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  updated_at: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  deleted_at: string | null;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  body: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  conversation_id: string;
  /**
   *
   * @type {Conversation}
   * @memberof ChatMessage
   */
  conversation: Conversation;
  /**
   *
   * @type {ChatMessageRoleEnum}
   * @memberof ChatMessage
   */
  role: ChatMessageRoleEnum;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  response_from_id: string | null;
  /**
   *
   * @type {string}
   * @memberof ChatMessage
   */
  response_to_id: string | null;
}

/**
 * Attributes necessary for creating a ChatMessage object
 * @export
 * @interface ChatMessageCreate
 */
export interface ChatMessageCreate {
  /**
   *
   * @type {string}
   * @memberof ChatMessageCreate
   */
  body: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessageCreate
   */
  conversation_id?: string | null;
}
/**
 *
 * @export
 * @enum {string}
 */

export enum ChatMessageRoleEnum {
  HUMAN = 'human',
  ROBOT = 'robot',
}

/**
 * Conversation outbound attributes
 * @export
 * @interface Conversation
 */
export interface Conversation {
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  updated_at: string;
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  deleted_at: string | null;
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  subject: string;
  /**
   *
   * @type {string}
   * @memberof Conversation
   */
  started_by_id: string;
  /**
   *
   * @type {User}
   * @memberof Conversation
   */
  started_by: User;
}
/**
 *
 * @export
 * @interface ErrorAttributes
 */
export interface ErrorAttributes {
  /**
   *
   * @type {object}
   * @memberof ErrorAttributes
   */
  context: object | null;
  /**
   *
   * @type {Array<PathInner>}
   * @memberof ErrorAttributes
   */
  path: Array<PathInner>;
  /**
   *
   * @type {string}
   * @memberof ErrorAttributes
   */
  message: string;
  /**
   *
   * @type {any}
   * @memberof ErrorAttributes
   */
  value: any;
}
/**
 *
 * @export
 * @enum {string}
 */

export enum ErrorCode {
  CHALLENGE_FAILED = 'CHALLENGE_FAILED',
  MISSING_RESOURCE = 'MISSING_RESOURCE',
  CONFLICT = 'CONFLICT',
  FORBIDDEN_REQUEST = 'FORBIDDEN_REQUEST',
  INVALID_REQUEST = 'INVALID_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNKNOWN = 'UNKNOWN',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
}

/**
 *
 * @export
 * @interface ErrorResponseConflictException
 */
export interface ErrorResponseConflictException {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseConflictException
   */
  message?: string;
  /**
   *
   * @type {boolean}
   * @memberof ErrorResponseConflictException
   */
  success?: boolean;
  /**
   *
   * @type {ErrorSpec}
   * @memberof ErrorResponseConflictException
   */
  error: ErrorSpec;
}
/**
 *
 * @export
 * @interface ErrorResponseForbiddenRequestException
 */
export interface ErrorResponseForbiddenRequestException {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseForbiddenRequestException
   */
  message?: string;
  /**
   *
   * @type {boolean}
   * @memberof ErrorResponseForbiddenRequestException
   */
  success?: boolean;
  /**
   *
   * @type {ErrorSpec}
   * @memberof ErrorResponseForbiddenRequestException
   */
  error: ErrorSpec;
}
/**
 *
 * @export
 * @interface ErrorResponseUnauthorizedException
 */
export interface ErrorResponseUnauthorizedException {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseUnauthorizedException
   */
  message?: string;
  /**
   *
   * @type {boolean}
   * @memberof ErrorResponseUnauthorizedException
   */
  success?: boolean;
  /**
   *
   * @type {ErrorSpec}
   * @memberof ErrorResponseUnauthorizedException
   */
  error: ErrorSpec;
}
/**
 *
 * @export
 * @interface ErrorResponseUnprocessableEntityException
 */
export interface ErrorResponseUnprocessableEntityException {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseUnprocessableEntityException
   */
  message?: string;
  /**
   *
   * @type {boolean}
   * @memberof ErrorResponseUnprocessableEntityException
   */
  success?: boolean;
  /**
   *
   * @type {ErrorSpec}
   * @memberof ErrorResponseUnprocessableEntityException
   */
  error: ErrorSpec;
}
/**
 *
 * @export
 * @interface ErrorSpec
 */
export interface ErrorSpec {
  /**
   *
   * @type {ErrorCode}
   * @memberof ErrorSpec
   */
  code: ErrorCode;
  /**
   *
   * @type {Array<ErrorAttributes>}
   * @memberof ErrorSpec
   */
  errors: Array<ErrorAttributes>;
}

/**
 *
 * @export
 * @interface PageCursor
 */
export interface PageCursor {}
/**
 *
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  top_cursor: string | null;
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  bottom_cursor: string | null;
  /**
   *
   * @type {boolean}
   * @memberof PageInfo
   */
  has_next: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PageInfo
   */
  has_prev: boolean;
}
/**
 *
 * @export
 * @interface PathInner
 */
export interface PathInner {}
/**
 *
 * @export
 * @interface ResponseMetadata
 */
export interface ResponseMetadata {
  /**
   *
   * @type {number}
   * @memberof ResponseMetadata
   */
  total_objects: number;
  /**
   *
   * @type {PageInfo}
   * @memberof ResponseMetadata
   */
  page_info: PageInfo;
}
/**
 *
 * @export
 * @interface StandardPaginatedResponseConversation
 */
export interface StandardPaginatedResponseConversation {
  /**
   *
   * @type {Array<Conversation>}
   * @memberof StandardPaginatedResponseConversation
   */
  data: Array<Conversation>;
  /**
   *
   * @type {ResponseMetadata}
   * @memberof StandardPaginatedResponseConversation
   */
  metadata: ResponseMetadata;
  /**
   *
   * @type {string}
   * @memberof StandardPaginatedResponseConversation
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StandardResponseAccount
 */
export interface StandardResponseAccount {
  /**
   *
   * @type {Account}
   * @memberof StandardResponseAccount
   */
  data: Account;
  /**
   *
   * @type {string}
   * @memberof StandardResponseAccount
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StandardResponseChatMessage
 */
export interface StandardResponseChatMessage {
  /**
   *
   * @type {ChatMessage}
   * @memberof StandardResponseChatMessage
   */
  data: ChatMessage;
  /**
   *
   * @type {string}
   * @memberof StandardResponseChatMessage
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StandardResponseConversation
 */
export interface StandardResponseConversation {
  /**
   *
   * @type {Conversation}
   * @memberof StandardResponseConversation
   */
  data: Conversation;
  /**
   *
   * @type {string}
   * @memberof StandardResponseConversation
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StandardResponseUser
 */
export interface StandardResponseUser {
  /**
   *
   * @type {User}
   * @memberof StandardResponseUser
   */
  data: User;
  /**
   *
   * @type {string}
   * @memberof StandardResponseUser
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StatusResponseAccount
 */
export interface StatusResponseAccount {
  /**
   *
   * @type {string}
   * @memberof StatusResponseAccount
   */
  message: string;
  /**
   *
   * @type {boolean}
   * @memberof StatusResponseAccount
   */
  success: boolean;
  /**
   *
   * @type {Account}
   * @memberof StatusResponseAccount
   */
  data: Account;
  /**
   *
   * @type {string}
   * @memberof StatusResponseAccount
   */
  typename: string;
}
/**
 *
 * @export
 * @interface StatusResponseChatMessage
 */
export interface StatusResponseChatMessage {
  /**
   *
   * @type {string}
   * @memberof StatusResponseChatMessage
   */
  message: string;
  /**
   *
   * @type {boolean}
   * @memberof StatusResponseChatMessage
   */
  success: boolean;
  /**
   *
   * @type {ChatMessage}
   * @memberof StatusResponseChatMessage
   */
  data: ChatMessage;
  /**
   *
   * @type {string}
   * @memberof StatusResponseChatMessage
   */
  typename: string;
}
/**
 *
 * @export
 * @interface Subject
 */
export interface Subject {}
/**
 * Token outbound attributes
 * @export
 * @interface Token
 */
export interface Token {
  /**
   * This class serves as a convenient representation     of a JWT RS256 Token, and also a valid Pydantic model     for representing this type of JWT token.      The signing algorithm used is an RS256 algorithm with     asymmetric key-pairs for signing and verifying, or encoding     and decoding.      It\'s safe to pass this object as a FastAPI or Pydantic     response model. It will be correctly represented as the     token string it wraps around, since it implements a     Pydantic model serializer.      To encode or sign a token from a regular Python data, dict,     you do not need to create this class object directly—the use     of `JWTRS256Token.from_data` covers this case.      The class object itself is used to wrap or represent an     already signed token string and can be used for decoding     the wrapped token.
   * @type {object}
   * @memberof Token
   */
  access_token: object;
  /**
   * This class serves as a convenient representation     of a JWT RS256 Token, and also a valid Pydantic model     for representing this type of JWT token.      The signing algorithm used is an RS256 algorithm with     asymmetric key-pairs for signing and verifying, or encoding     and decoding.      It\'s safe to pass this object as a FastAPI or Pydantic     response model. It will be correctly represented as the     token string it wraps around, since it implements a     Pydantic model serializer.      To encode or sign a token from a regular Python data, dict,     you do not need to create this class object directly—the use     of `JWTRS256Token.from_data` covers this case.      The class object itself is used to wrap or represent an     already signed token string and can be used for decoding     the wrapped token.
   * @type {object}
   * @memberof Token
   */
  refresh_token: object;
  /**
   *
   * @type {string}
   * @memberof Token
   */
  token_type: string;
}
/**
 * User outbound attributes
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  updated_at: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  deleted_at: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  first_name: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  last_name: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  account_id: string;
}
/**
 * Attributes necessary for creating a User object
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  first_name: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  last_name: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  username: string;
}

/**
 * AccountApi - axios parameter creator
 * @export
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * OAuth2 authentication for clients.  Provides an access and refresh token. The access token can be used to request resources requiring authorization, while the refresh token can be used to re-authenticate, providing a fresh token when the previous access token expires.  Request form body takes username and password, essentially, to authenticate; where username can be anything, an email address or a \"username\". In this case the application expects it to be an email address.  A refresh_token is expected in lieu of a username and password, with a grant_type of \"refresh_token\" for a reauthentication request.
     * @summary Authenticate User Account
     * @param {string} username
     * @param {string | null} [grantType]
     * @param {string} [password]
     * @param {string} [refreshToken]
     * @param {string} [scope]
     * @param {string | null} [clientId]
     * @param {string | null} [clientSecret]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateUserAccountAccountsAuthenticatePost: async (
      username: string,
      grantType?: string | null,
      password?: string,
      refreshToken?: string,
      scope?: string,
      clientId?: string | null,
      clientSecret?: string | null,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'username' is not null or undefined
      assertParamExists('authenticateUserAccountAccountsAuthenticatePost', 'username', username);
      const localVarPath = `/accounts/authenticate`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;
      const localVarFormParams = new URLSearchParams();

      if (grantType !== undefined) {
        localVarFormParams.set('grant_type', grantType as any);
      }

      if (username !== undefined) {
        localVarFormParams.set('username', username as any);
      }

      if (password !== undefined) {
        localVarFormParams.set('password', password as any);
      }

      if (refreshToken !== undefined) {
        localVarFormParams.set('refresh_token', refreshToken as any);
      }

      if (scope !== undefined) {
        localVarFormParams.set('scope', scope as any);
      }

      if (clientId !== undefined) {
        localVarFormParams.set('client_id', clientId as any);
      }

      if (clientSecret !== undefined) {
        localVarFormParams.set('client_secret', clientSecret as any);
      }

      localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = localVarFormParams.toString();

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create a user account
     * @summary Create User Account
     * @param {AccountCreate} accountCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUserAccountAccountsCreatePost: async (
      accountCreate: AccountCreate,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountCreate' is not null or undefined
      assertParamExists('createUserAccountAccountsCreatePost', 'accountCreate', accountCreate);
      const localVarPath = `/accounts/create`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(accountCreate, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Identify the current user and return the user account
     * @summary Identify User Account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    identifyUserAccountAccountsMeGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/accounts/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication OAuth2PasswordBearer required
      // oauth required
      await setOAuthToObject(localVarHeaderParameter, 'OAuth2PasswordBearer', [], configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AccountApi - functional programming interface
 * @export
 */
export const AccountApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration);
  return {
    /**
     * OAuth2 authentication for clients.  Provides an access and refresh token. The access token can be used to request resources requiring authorization, while the refresh token can be used to re-authenticate, providing a fresh token when the previous access token expires.  Request form body takes username and password, essentially, to authenticate; where username can be anything, an email address or a \"username\". In this case the application expects it to be an email address.  A refresh_token is expected in lieu of a username and password, with a grant_type of \"refresh_token\" for a reauthentication request.
     * @summary Authenticate User Account
     * @param {string} username
     * @param {string | null} [grantType]
     * @param {string} [password]
     * @param {string} [refreshToken]
     * @param {string} [scope]
     * @param {string | null} [clientId]
     * @param {string | null} [clientSecret]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async authenticateUserAccountAccountsAuthenticatePost(
      username: string,
      grantType?: string | null,
      password?: string,
      refreshToken?: string,
      scope?: string,
      clientId?: string | null,
      clientSecret?: string | null,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Token>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.authenticateUserAccountAccountsAuthenticatePost(
        username,
        grantType,
        password,
        refreshToken,
        scope,
        clientId,
        clientSecret,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Create a user account
     * @summary Create User Account
     * @param {AccountCreate} accountCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createUserAccountAccountsCreatePost(
      accountCreate: AccountCreate,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponseAccount>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createUserAccountAccountsCreatePost(
        accountCreate,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Identify the current user and return the user account
     * @summary Identify User Account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async identifyUserAccountAccountsMeGet(
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseAccount>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.identifyUserAccountAccountsMeGet(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * AccountApi - factory interface
 * @export
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = AccountApiFp(configuration);
  return {
    /**
     * OAuth2 authentication for clients.  Provides an access and refresh token. The access token can be used to request resources requiring authorization, while the refresh token can be used to re-authenticate, providing a fresh token when the previous access token expires.  Request form body takes username and password, essentially, to authenticate; where username can be anything, an email address or a \"username\". In this case the application expects it to be an email address.  A refresh_token is expected in lieu of a username and password, with a grant_type of \"refresh_token\" for a reauthentication request.
     * @summary Authenticate User Account
     * @param {AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authenticateUserAccountAccountsAuthenticatePost(
      requestParameters: AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<Token> {
      return localVarFp
        .authenticateUserAccountAccountsAuthenticatePost(
          requestParameters.username,
          requestParameters.grantType,
          requestParameters.password,
          requestParameters.refreshToken,
          requestParameters.scope,
          requestParameters.clientId,
          requestParameters.clientSecret,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create a user account
     * @summary Create User Account
     * @param {AccountApiCreateUserAccountAccountsCreatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUserAccountAccountsCreatePost(
      requestParameters: AccountApiCreateUserAccountAccountsCreatePostRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StatusResponseAccount> {
      return localVarFp
        .createUserAccountAccountsCreatePost(requestParameters.accountCreate, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Identify the current user and return the user account
     * @summary Identify User Account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    identifyUserAccountAccountsMeGet(options?: AxiosRequestConfig): AxiosPromise<StandardResponseAccount> {
      return localVarFp.identifyUserAccountAccountsMeGet(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for authenticateUserAccountAccountsAuthenticatePost operation in AccountApi.
 * @export
 * @interface AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest
 */
export interface AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest {
  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly username: string;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly grantType?: string | null;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly password?: string;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly refreshToken?: string;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly scope?: string;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly clientId?: string | null;

  /**
   *
   * @type {string}
   * @memberof AccountApiAuthenticateUserAccountAccountsAuthenticatePost
   */
  readonly clientSecret?: string | null;
}

/**
 * Request parameters for createUserAccountAccountsCreatePost operation in AccountApi.
 * @export
 * @interface AccountApiCreateUserAccountAccountsCreatePostRequest
 */
export interface AccountApiCreateUserAccountAccountsCreatePostRequest {
  /**
   *
   * @type {AccountCreate}
   * @memberof AccountApiCreateUserAccountAccountsCreatePost
   */
  readonly accountCreate: AccountCreate;
}

/**
 * AccountApi - object-oriented interface
 * @export
 * @class AccountApi
 * @extends {BaseAPI}
 */
export class AccountApi extends BaseAPI {
  /**
   * OAuth2 authentication for clients.  Provides an access and refresh token. The access token can be used to request resources requiring authorization, while the refresh token can be used to re-authenticate, providing a fresh token when the previous access token expires.  Request form body takes username and password, essentially, to authenticate; where username can be anything, an email address or a \"username\". In this case the application expects it to be an email address.  A refresh_token is expected in lieu of a username and password, with a grant_type of \"refresh_token\" for a reauthentication request.
   * @summary Authenticate User Account
   * @param {AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AccountApi
   */
  public authenticateUserAccountAccountsAuthenticatePost(
    requestParameters: AccountApiAuthenticateUserAccountAccountsAuthenticatePostRequest,
    options?: AxiosRequestConfig,
  ) {
    return AccountApiFp(this.configuration)
      .authenticateUserAccountAccountsAuthenticatePost(
        requestParameters.username,
        requestParameters.grantType,
        requestParameters.password,
        requestParameters.refreshToken,
        requestParameters.scope,
        requestParameters.clientId,
        requestParameters.clientSecret,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create a user account
   * @summary Create User Account
   * @param {AccountApiCreateUserAccountAccountsCreatePostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AccountApi
   */
  public createUserAccountAccountsCreatePost(
    requestParameters: AccountApiCreateUserAccountAccountsCreatePostRequest,
    options?: AxiosRequestConfig,
  ) {
    return AccountApiFp(this.configuration)
      .createUserAccountAccountsCreatePost(requestParameters.accountCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Identify the current user and return the user account
   * @summary Identify User Account
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AccountApi
   */
  public identifyUserAccountAccountsMeGet(options?: AxiosRequestConfig) {
    return AccountApiFp(this.configuration)
      .identifyUserAccountAccountsMeGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * ChatApi - axios parameter creator
 * @export
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Publish a prompt message to be handled by various connecting services.  Pre-listen on a websocket connection with the conversation id of the published prompt message for a response stream to the prompt message itself.
     * @summary Publish Message
     * @param {ChatMessageCreate} chatMessageCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    publishMessageChatsMessagePost: async (
      chatMessageCreate: ChatMessageCreate,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'chatMessageCreate' is not null or undefined
      assertParamExists('publishMessageChatsMessagePost', 'chatMessageCreate', chatMessageCreate);
      const localVarPath = `/chats/message`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication OAuth2PasswordBearer required
      // oauth required
      await setOAuthToObject(localVarHeaderParameter, 'OAuth2PasswordBearer', [], configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(chatMessageCreate, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Read a message by a given id.
     * @summary Read Chat Message By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readChatMessageByIdChatsMessageIdGet: async (
      id: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('readChatMessageByIdChatsMessageIdGet', 'id', id);
      const localVarPath = `/chats/message/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication OAuth2PasswordBearer required
      // oauth required
      await setOAuthToObject(localVarHeaderParameter, 'OAuth2PasswordBearer', [], configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ChatApi - functional programming interface
 * @export
 */
export const ChatApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration);
  return {
    /**
     * Publish a prompt message to be handled by various connecting services.  Pre-listen on a websocket connection with the conversation id of the published prompt message for a response stream to the prompt message itself.
     * @summary Publish Message
     * @param {ChatMessageCreate} chatMessageCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async publishMessageChatsMessagePost(
      chatMessageCreate: ChatMessageCreate,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponseChatMessage>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.publishMessageChatsMessagePost(
        chatMessageCreate,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Read a message by a given id.
     * @summary Read Chat Message By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async readChatMessageByIdChatsMessageIdGet(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseChatMessage>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.readChatMessageByIdChatsMessageIdGet(id, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * ChatApi - factory interface
 * @export
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ChatApiFp(configuration);
  return {
    /**
     * Publish a prompt message to be handled by various connecting services.  Pre-listen on a websocket connection with the conversation id of the published prompt message for a response stream to the prompt message itself.
     * @summary Publish Message
     * @param {ChatApiPublishMessageChatsMessagePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    publishMessageChatsMessagePost(
      requestParameters: ChatApiPublishMessageChatsMessagePostRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StatusResponseChatMessage> {
      return localVarFp
        .publishMessageChatsMessagePost(requestParameters.chatMessageCreate, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Read a message by a given id.
     * @summary Read Chat Message By Id
     * @param {ChatApiReadChatMessageByIdChatsMessageIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readChatMessageByIdChatsMessageIdGet(
      requestParameters: ChatApiReadChatMessageByIdChatsMessageIdGetRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StandardResponseChatMessage> {
      return localVarFp
        .readChatMessageByIdChatsMessageIdGet(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for publishMessageChatsMessagePost operation in ChatApi.
 * @export
 * @interface ChatApiPublishMessageChatsMessagePostRequest
 */
export interface ChatApiPublishMessageChatsMessagePostRequest {
  /**
   *
   * @type {ChatMessageCreate}
   * @memberof ChatApiPublishMessageChatsMessagePost
   */
  readonly chatMessageCreate: ChatMessageCreate;
}

/**
 * Request parameters for readChatMessageByIdChatsMessageIdGet operation in ChatApi.
 * @export
 * @interface ChatApiReadChatMessageByIdChatsMessageIdGetRequest
 */
export interface ChatApiReadChatMessageByIdChatsMessageIdGetRequest {
  /**
   *
   * @type {string}
   * @memberof ChatApiReadChatMessageByIdChatsMessageIdGet
   */
  readonly id: string;
}

/**
 * ChatApi - object-oriented interface
 * @export
 * @class ChatApi
 * @extends {BaseAPI}
 */
export class ChatApi extends BaseAPI {
  /**
   * Publish a prompt message to be handled by various connecting services.  Pre-listen on a websocket connection with the conversation id of the published prompt message for a response stream to the prompt message itself.
   * @summary Publish Message
   * @param {ChatApiPublishMessageChatsMessagePostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ChatApi
   */
  public publishMessageChatsMessagePost(
    requestParameters: ChatApiPublishMessageChatsMessagePostRequest,
    options?: AxiosRequestConfig,
  ) {
    return ChatApiFp(this.configuration)
      .publishMessageChatsMessagePost(requestParameters.chatMessageCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Read a message by a given id.
   * @summary Read Chat Message By Id
   * @param {ChatApiReadChatMessageByIdChatsMessageIdGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ChatApi
   */
  public readChatMessageByIdChatsMessageIdGet(
    requestParameters: ChatApiReadChatMessageByIdChatsMessageIdGetRequest,
    options?: AxiosRequestConfig,
  ) {
    return ChatApiFp(this.configuration)
      .readChatMessageByIdChatsMessageIdGet(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * ConversationApi - axios parameter creator
 * @export
 */
export const ConversationApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Read a conversation by a given id.
     * @summary Read Conversation By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readConversationByIdConversationsIdGet: async (
      id: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('readConversationByIdConversationsIdGet', 'id', id);
      const localVarPath = `/conversations/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication OAuth2PasswordBearer required
      // oauth required
      await setOAuthToObject(localVarHeaderParameter, 'OAuth2PasswordBearer', [], configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Read Conversations
     * @param {string} [sort] id, created_at, updated_at, deleted_at, subject, started_by_id, started_by (e.g, id:1754)
     * @param {Subject | null} [subject]
     * @param {PageCursor | null} [pageCursor]
     * @param {number} [pageSize]
     * @param {boolean} [pageForward]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readConversationsConversationsGet: async (
      sort?: string,
      subject?: Subject | null,
      pageCursor?: PageCursor | null,
      pageSize?: number,
      pageForward?: boolean,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/conversations/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication OAuth2PasswordBearer required
      // oauth required
      await setOAuthToObject(localVarHeaderParameter, 'OAuth2PasswordBearer', [], configuration);

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort;
      }

      if (subject !== undefined) {
        localVarQueryParameter['subject'] = subject;
      }

      if (pageCursor !== undefined) {
        localVarQueryParameter['page_cursor'] = pageCursor;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter['page_size'] = pageSize;
      }

      if (pageForward !== undefined) {
        localVarQueryParameter['page_forward'] = pageForward;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ConversationApi - functional programming interface
 * @export
 */
export const ConversationApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ConversationApiAxiosParamCreator(configuration);
  return {
    /**
     * Read a conversation by a given id.
     * @summary Read Conversation By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async readConversationByIdConversationsIdGet(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseConversation>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.readConversationByIdConversationsIdGet(id, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Read Conversations
     * @param {string} [sort] id, created_at, updated_at, deleted_at, subject, started_by_id, started_by (e.g, id:1754)
     * @param {Subject | null} [subject]
     * @param {PageCursor | null} [pageCursor]
     * @param {number} [pageSize]
     * @param {boolean} [pageForward]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async readConversationsConversationsGet(
      sort?: string,
      subject?: Subject | null,
      pageCursor?: PageCursor | null,
      pageSize?: number,
      pageForward?: boolean,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardPaginatedResponseConversation>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.readConversationsConversationsGet(
        sort,
        subject,
        pageCursor,
        pageSize,
        pageForward,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * ConversationApi - factory interface
 * @export
 */
export const ConversationApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ConversationApiFp(configuration);
  return {
    /**
     * Read a conversation by a given id.
     * @summary Read Conversation By Id
     * @param {ConversationApiReadConversationByIdConversationsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readConversationByIdConversationsIdGet(
      requestParameters: ConversationApiReadConversationByIdConversationsIdGetRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StandardResponseConversation> {
      return localVarFp
        .readConversationByIdConversationsIdGet(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Read Conversations
     * @param {ConversationApiReadConversationsConversationsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readConversationsConversationsGet(
      requestParameters: ConversationApiReadConversationsConversationsGetRequest = {},
      options?: AxiosRequestConfig,
    ): AxiosPromise<StandardPaginatedResponseConversation> {
      return localVarFp
        .readConversationsConversationsGet(
          requestParameters.sort,
          requestParameters.subject,
          requestParameters.pageCursor,
          requestParameters.pageSize,
          requestParameters.pageForward,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for readConversationByIdConversationsIdGet operation in ConversationApi.
 * @export
 * @interface ConversationApiReadConversationByIdConversationsIdGetRequest
 */
export interface ConversationApiReadConversationByIdConversationsIdGetRequest {
  /**
   *
   * @type {string}
   * @memberof ConversationApiReadConversationByIdConversationsIdGet
   */
  readonly id: string;
}

/**
 * Request parameters for readConversationsConversationsGet operation in ConversationApi.
 * @export
 * @interface ConversationApiReadConversationsConversationsGetRequest
 */
export interface ConversationApiReadConversationsConversationsGetRequest {
  /**
   * id, created_at, updated_at, deleted_at, subject, started_by_id, started_by (e.g, id:1754)
   * @type {string}
   * @memberof ConversationApiReadConversationsConversationsGet
   */
  readonly sort?: string;

  /**
   *
   * @type {Subject}
   * @memberof ConversationApiReadConversationsConversationsGet
   */
  readonly subject?: Subject | null;

  /**
   *
   * @type {PageCursor}
   * @memberof ConversationApiReadConversationsConversationsGet
   */
  readonly pageCursor?: PageCursor | null;

  /**
   *
   * @type {number}
   * @memberof ConversationApiReadConversationsConversationsGet
   */
  readonly pageSize?: number;

  /**
   *
   * @type {boolean}
   * @memberof ConversationApiReadConversationsConversationsGet
   */
  readonly pageForward?: boolean;
}

/**
 * ConversationApi - object-oriented interface
 * @export
 * @class ConversationApi
 * @extends {BaseAPI}
 */
export class ConversationApi extends BaseAPI {
  /**
   * Read a conversation by a given id.
   * @summary Read Conversation By Id
   * @param {ConversationApiReadConversationByIdConversationsIdGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConversationApi
   */
  public readConversationByIdConversationsIdGet(
    requestParameters: ConversationApiReadConversationByIdConversationsIdGetRequest,
    options?: AxiosRequestConfig,
  ) {
    return ConversationApiFp(this.configuration)
      .readConversationByIdConversationsIdGet(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Read Conversations
   * @param {ConversationApiReadConversationsConversationsGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConversationApi
   */
  public readConversationsConversationsGet(
    requestParameters: ConversationApiReadConversationsConversationsGetRequest = {},
    options?: AxiosRequestConfig,
  ) {
    return ConversationApiFp(this.configuration)
      .readConversationsConversationsGet(
        requestParameters.sort,
        requestParameters.subject,
        requestParameters.pageCursor,
        requestParameters.pageSize,
        requestParameters.pageForward,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * RootApi - axios parameter creator
 * @export
 */
export const RootApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Returns basic information about the application
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rootGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RootApi - functional programming interface
 * @export
 */
export const RootApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RootApiAxiosParamCreator(configuration);
  return {
    /**
     * Returns basic information about the application
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rootGet(
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationInfo>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * RootApi - factory interface
 * @export
 */
export const RootApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = RootApiFp(configuration);
  return {
    /**
     * Returns basic information about the application
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rootGet(options?: AxiosRequestConfig): AxiosPromise<ApplicationInfo> {
      return localVarFp.rootGet(options).then((request) => request(axios, basePath));
    },
  };
};

/**
 * RootApi - object-oriented interface
 * @export
 * @class RootApi
 * @extends {BaseAPI}
 */
export class RootApi extends BaseAPI {
  /**
   * Returns basic information about the application
   * @summary Root
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApi
   */
  public rootGet(options?: AxiosRequestConfig) {
    return RootApiFp(this.configuration)
      .rootGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Find User By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findUserByIdUsersIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('findUserByIdUsersIdGet', 'id', id);
      const localVarPath = `/users/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Find User By Username
     * @param {string} username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findUserByUsernameUsersByUsernameGet: async (
      username: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'username' is not null or undefined
      assertParamExists('findUserByUsernameUsersByUsernameGet', 'username', username);
      const localVarPath = `/users/by_username`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (username !== undefined) {
        localVarQueryParameter['username'] = username;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Find User By Id
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async findUserByIdUsersIdGet(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseUser>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.findUserByIdUsersIdGet(id, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     *
     * @summary Find User By Username
     * @param {string} username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async findUserByUsernameUsersByUsernameGet(
      username: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseUser>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.findUserByUsernameUsersByUsernameGet(username, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = UserApiFp(configuration);
  return {
    /**
     *
     * @summary Find User By Id
     * @param {UserApiFindUserByIdUsersIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findUserByIdUsersIdGet(
      requestParameters: UserApiFindUserByIdUsersIdGetRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StandardResponseUser> {
      return localVarFp
        .findUserByIdUsersIdGet(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Find User By Username
     * @param {UserApiFindUserByUsernameUsersByUsernameGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findUserByUsernameUsersByUsernameGet(
      requestParameters: UserApiFindUserByUsernameUsersByUsernameGetRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<StandardResponseUser> {
      return localVarFp
        .findUserByUsernameUsersByUsernameGet(requestParameters.username, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for findUserByIdUsersIdGet operation in UserApi.
 * @export
 * @interface UserApiFindUserByIdUsersIdGetRequest
 */
export interface UserApiFindUserByIdUsersIdGetRequest {
  /**
   *
   * @type {string}
   * @memberof UserApiFindUserByIdUsersIdGet
   */
  readonly id: string;
}

/**
 * Request parameters for findUserByUsernameUsersByUsernameGet operation in UserApi.
 * @export
 * @interface UserApiFindUserByUsernameUsersByUsernameGetRequest
 */
export interface UserApiFindUserByUsernameUsersByUsernameGetRequest {
  /**
   *
   * @type {string}
   * @memberof UserApiFindUserByUsernameUsersByUsernameGet
   */
  readonly username: string;
}

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
  /**
   *
   * @summary Find User By Id
   * @param {UserApiFindUserByIdUsersIdGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public findUserByIdUsersIdGet(requestParameters: UserApiFindUserByIdUsersIdGetRequest, options?: AxiosRequestConfig) {
    return UserApiFp(this.configuration)
      .findUserByIdUsersIdGet(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Find User By Username
   * @param {UserApiFindUserByUsernameUsersByUsernameGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApi
   */
  public findUserByUsernameUsersByUsernameGet(
    requestParameters: UserApiFindUserByUsernameUsersByUsernameGetRequest,
    options?: AxiosRequestConfig,
  ) {
    return UserApiFp(this.configuration)
      .findUserByUsernameUsersByUsernameGet(requestParameters.username, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
