/* tslint:disable */
/* eslint-disable */
/**
 * Casandra
 * Casandra is a study assistant that consumes study materials, proposes and answers questions based on the provided materials.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
