import Cookies from 'js-cookie';
import { AuthOptions, DefaultSession, Session } from 'next-auth';
import { JWT } from 'next-auth/jwt';
import CredentialsProvider from 'next-auth/providers/credentials';
import GoogleProvider from 'next-auth/providers/google';
import { BuiltInProviderType } from 'next-auth/providers/index';

import { AccountProviderEnum, StandardResponseAccount, StatusResponseAccount, Token } from '@/client';
import {
  APP_NAME,
  AUTH_INTENT_KEY,
  getAuthorization,
  GOOGLE_ID,
  GOOGLE_SECRET,
  never,
  NonNullableMembers,
} from '@/core/utils';
import { Routes } from '@/core/utils/routes';

import {
  authenticateAccountOIDCService,
  authenticateAccountService,
  createAccountOIDCService,
  identifyUserAccountService,
  SigninCredentials,
} from '../account';

export type AuthIntent = 'access' | 'register';

export interface CasandraSessionUser extends NonNullableMembers<NonNullable<DefaultSession['user']>> {
  /** @note This is the user id not the user account id */
  id?: string;
  /** @note This is the token generated by the application itself not any 3rd party */
  tokens?: Token;
}

export const setAuthIntent = (intent: AuthIntent) => {
  return Cookies.set(AUTH_INTENT_KEY, intent, {
    secure: process.env.NODE_ENV !== 'development',
  });
};
export const resetAuthIntent = () => Cookies.remove(AUTH_INTENT_KEY);

export const getAuthOptions: (intent: AuthIntent) => AuthOptions = (intent) => {
  return {
    pages: { signIn: Routes.SIGNIN, newUser: Routes.CONVERSATIONS_NEW },
    providers: [
      GoogleProvider({ clientId: GOOGLE_ID, clientSecret: GOOGLE_SECRET }),
      CredentialsProvider({
        name: `${APP_NAME} Account`,
        credentials: {
          email: { label: 'Email address', type: 'email' },
          password: { label: 'Password', type: 'Password' },
        },
        async authorize(credentials: SigninCredentials | undefined, _req) {
          if (!credentials) return null;
          const { data: token } = await authenticateAccountService(credentials);
          const { data: identity } = await identifyUserAccountService({
            headers: { Authorization: getAuthorization(token) },
          });

          const account = identity.data;

          return {
            id: account.user.id,
            email: account.email,
            name: account.user.fullname,
            image: '',
            tokens: token,
          };
        },
      }),
    ],
    callbacks: {
      async jwt(params) {
        const jwt = params.token;

        if (params.trigger === 'signIn') {
          const account = params.account!; // account is available when trigger is "signIn"
          const provider = account.provider as BuiltInProviderType;
          const user = params.user; // user is available when trigger is "signIn"

          switch (provider) {
            case 'credentials': {
              Object.assign(jwt, { tokens: user.tokens });
              break;
            }

            case 'google': {
              let identity: StatusResponseAccount | StandardResponseAccount | undefined = undefined;

              if (!account.access_token || !account.id_token) {
                throw new Error(`Access token and ID token are missing in the ${provider} provider`);
              }

              const credentials = {
                access_token: account.access_token,
                id_token: account.id_token,
                provider: AccountProviderEnum.GOOGLE,
              };

              switch (intent) {
                case 'access':
                  // noop
                  break;
                case 'register':
                  ({ data: identity } = await createAccountOIDCService(credentials));
                  break;
                default:
                  never(intent);
              }

              // After registration we'll still authenticate (access) anyway. So "access" case above is a no-op
              const res = await authenticateAccountOIDCService(credentials);
              const token = res.data;

              // identity will be undefined for intent="access" but will be of type StatusResponseAccount if "register"
              if (!identity) {
                ({ data: identity } = await identifyUserAccountService({
                  headers: { Authorization: getAuthorization(token) },
                }));
              }

              Object.assign<JWT, JWT>(jwt, { tokens: token, sub: identity.data.user.id });
              break;
            }

            default:
              never(provider as never);
          }
        } else if (params.trigger === 'update') {
          // TODO: validate params.session
          const update: Session = params.session;
          Object.assign<JWT, JWT>(jwt, {
            tokens: update.tokens,
            email: update.user.email,
            name: update.user.name,
            picture: update.user.image,
            sub: update.user.id,
          });
        }

        return jwt;
      },
      session(params) {
        params.session.user.id = params.token.sub;
        params.session.tokens = params.token.tokens;

        return params.session;
      },
    },
  };
};
