FROM node:16-alpine

# Define working directory for client
WORKDIR /kaysolo/dissertation/kaybot

# Copy package metadata for client
COPY ./package.json .
COPY ./yarn.lock .

# Install dependencies
RUN yarn install --frozen-lockfile

