"""rename 'ChatMessage' and update columns

Revision ID: 1dc466290051
Revises: 778866cf38ff
Create Date: 2023-09-27 00:33:57.490832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dc466290051'
down_revision: Union[str, None] = '778866cf38ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConversationMessage',
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('human', 'robot', name='conversationmessageroleenum'), nullable=False),
    sa.Column('response_to_id', sa.Uuid(), nullable=True),
    sa.Column('response_from_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='ConversationMessages_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_from_id'], ['ConversationMessage.id'], name='ConversationMessage_response_from_id_fkey'),
    sa.ForeignKeyConstraint(['response_to_id'], ['ConversationMessage.id'], name='ConversationMessage_response_to_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_from_id'),
    sa.UniqueConstraint('response_to_id')
    )
    op.create_index(op.f('ix_ConversationMessage_created_at'), 'ConversationMessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_deleted_at'), 'ConversationMessage', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_id'), 'ConversationMessage', ['id'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_updated_at'), 'ConversationMessage', ['updated_at'], unique=False)
    op.create_table('QuotedMessagesToQuotingMessagesAssocTable',
    sa.Column('quoting_id', sa.Uuid(), nullable=False),
    sa.Column('quoted_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quoted_id'], ['ConversationMessage.id'], name='ConversationMessage_quoted_id_fkey'),
    sa.ForeignKeyConstraint(['quoting_id'], ['ConversationMessage.id'], name='ConversationMessage_quoting_id_fkey'),
    sa.PrimaryKeyConstraint('quoting_id', 'quoted_id')
    )
    op.drop_index('ix_ChatMessage_created_at', table_name='ChatMessage')
    op.drop_index('ix_ChatMessage_deleted_at', table_name='ChatMessage')
    op.drop_index('ix_ChatMessage_id', table_name='ChatMessage')
    op.drop_index('ix_ChatMessage_updated_at', table_name='ChatMessage')
    op.drop_table('ChatMessage')
    op.create_index(op.f('ix_Conversation_subject'), 'Conversation', ['subject'], unique=False)
    op.drop_constraint('Conversations_user_id_fkey', 'Conversation', type_='foreignkey')
    op.create_foreign_key('Conversations_user_id_fkey', 'Conversation', 'User', ['started_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('User_account_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key('User_account_id_fkey', 'User', 'Account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_account_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key('User_account_id_fkey', 'User', 'Account', ['account_id'], ['id'])
    op.drop_constraint('Conversations_user_id_fkey', 'Conversation', type_='foreignkey')
    op.create_foreign_key('Conversations_user_id_fkey', 'Conversation', 'User', ['started_by_id'], ['id'])
    op.drop_index(op.f('ix_Conversation_subject'), table_name='Conversation')
    op.create_table('ChatMessage',
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('human', 'robot', name='chatmessageroleenum'), autoincrement=False, nullable=False),
    sa.Column('response_to_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('response_from_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_dangling', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='ChatMessages_conversation_id_fkey'),
    sa.ForeignKeyConstraint(['response_from_id'], ['ChatMessage.id'], name='ChatMessage_response_from_id_fkey'),
    sa.ForeignKeyConstraint(['response_to_id'], ['ChatMessage.id'], name='ChatMessage_response_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ChatMessage_pkey')
    )
    op.create_index('ix_ChatMessage_updated_at', 'ChatMessage', ['updated_at'], unique=False)
    op.create_index('ix_ChatMessage_id', 'ChatMessage', ['id'], unique=False)
    op.create_index('ix_ChatMessage_deleted_at', 'ChatMessage', ['deleted_at'], unique=False)
    op.create_index('ix_ChatMessage_created_at', 'ChatMessage', ['created_at'], unique=False)
    op.drop_table('QuotedMessagesToQuotingMessagesAssocTable')
    op.drop_index(op.f('ix_ConversationMessage_updated_at'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_id'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_deleted_at'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_created_at'), table_name='ConversationMessage')
    op.drop_table('ConversationMessage')
    # ### end Alembic commands ###
