"""Add 'last_active_at' column to Conversation

Revision ID: 26ada0c0f5d0
Revises: 1dc466290051
Create Date: 2023-10-01 12:49:52.905990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ada0c0f5d0'
down_revision: Union[str, None] = '1dc466290051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Conversation', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_Conversation_last_active_at'), 'Conversation', ['last_active_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Conversation_last_active_at'), table_name='Conversation')
    op.drop_column('Conversation', 'last_active_at')
    # ### end Alembic commands ###
