"""create tables

Revision ID: 53f98e8f5f55
Revises: 
Create Date: 2023-08-31 16:38:40.229011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f98e8f5f55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_Account_email_UNIQUE', 'Account', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_Account_created_at'), 'Account', ['created_at'], unique=False)
    op.create_index(op.f('ix_Account_deleted_at'), 'Account', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_Account_id'), 'Account', ['id'], unique=False)
    op.create_index(op.f('ix_Account_updated_at'), 'Account', ['updated_at'], unique=False)
    op.create_table('User',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Account.id'], name='User_account_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index('IDX_User_username_UNIQUE', 'User', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_User_created_at'), 'User', ['created_at'], unique=False)
    op.create_index(op.f('ix_User_deleted_at'), 'User', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_updated_at'), 'User', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_updated_at'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_deleted_at'), table_name='User')
    op.drop_index(op.f('ix_User_created_at'), table_name='User')
    op.drop_index('IDX_User_username_UNIQUE', table_name='User', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('User')
    op.drop_index(op.f('ix_Account_updated_at'), table_name='Account')
    op.drop_index(op.f('ix_Account_id'), table_name='Account')
    op.drop_index(op.f('ix_Account_deleted_at'), table_name='Account')
    op.drop_index(op.f('ix_Account_created_at'), table_name='Account')
    op.drop_index('IDX_Account_email_UNIQUE', table_name='Account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('Account')
    # ### end Alembic commands ###
