"""add connected services table

Revision ID: 61aa9f762e5b
Revises: d904e8ec89f8
Create Date: 2023-11-05 11:10:02.500104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61aa9f762e5b'
down_revision: Union[str, None] = 'd904e8ec89f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConnectedServices',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', name='connectedservicesproviderenum'), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Account.id'], name='ConnectedServices_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_ConnectedServices_provider_label_UNIQUE', 'ConnectedServices', ['provider', 'label'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('IDX_ConnectedServices_provider_provider_account_id_UNIQUE', 'ConnectedServices', ['provider', 'provider_account_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_ConnectedServices_created_at'), 'ConnectedServices', ['created_at'], unique=False)
    op.create_index(op.f('ix_ConnectedServices_deleted_at'), 'ConnectedServices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ConnectedServices_id'), 'ConnectedServices', ['id'], unique=False)
    op.create_index(op.f('ix_ConnectedServices_updated_at'), 'ConnectedServices', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ConnectedServices_updated_at'), table_name='ConnectedServices')
    op.drop_index(op.f('ix_ConnectedServices_id'), table_name='ConnectedServices')
    op.drop_index(op.f('ix_ConnectedServices_deleted_at'), table_name='ConnectedServices')
    op.drop_index(op.f('ix_ConnectedServices_created_at'), table_name='ConnectedServices')
    op.drop_index('IDX_ConnectedServices_provider_provider_account_id_UNIQUE', table_name='ConnectedServices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('IDX_ConnectedServices_provider_label_UNIQUE', table_name='ConnectedServices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('ConnectedServices')
    # ### end Alembic commands ###
