"""add '_dangling' column (non-standard) to mark non-commited chat messages

Revision ID: 778866cf38ff
Revises: da9ec64f4f62
Create Date: 2023-09-05 09:35:40.466824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778866cf38ff'
down_revision: Union[str, None] = 'da9ec64f4f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChatMessage', sa.Column('_dangling', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChatMessage', '_dangling')
    # ### end Alembic commands ###
