"""create tables

Revision ID: d904e8ec89f8
Revises: 
Create Date: 2023-10-18 09:56:23.639493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd904e8ec89f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_Account_email_UNIQUE', 'Account', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_Account_created_at'), 'Account', ['created_at'], unique=False)
    op.create_index(op.f('ix_Account_deleted_at'), 'Account', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_Account_id'), 'Account', ['id'], unique=False)
    op.create_index(op.f('ix_Account_updated_at'), 'Account', ['updated_at'], unique=False)
    op.create_table('AccountMeta',
    sa.Column('provider', sa.Enum('google', 'apple', 'self', name='accountproviderenum'), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('provider_account_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Account.id'], name='AccountMeta_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index('IDX_AccountMeta_provider_provider_account_id_UNIQUE', 'AccountMeta', ['provider', 'provider_account_id'], unique=True, postgresql_where=sa.text("provider != 'self' AND deleted_at IS NULL"))
    op.create_index(op.f('ix_AccountMeta_created_at'), 'AccountMeta', ['created_at'], unique=False)
    op.create_index(op.f('ix_AccountMeta_deleted_at'), 'AccountMeta', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_AccountMeta_id'), 'AccountMeta', ['id'], unique=False)
    op.create_index(op.f('ix_AccountMeta_updated_at'), 'AccountMeta', ['updated_at'], unique=False)
    op.create_table('AccountPassword',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('hashed', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Account.id'], name='AccountPassword_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_AccountPassword_created_at'), 'AccountPassword', ['created_at'], unique=False)
    op.create_index(op.f('ix_AccountPassword_deleted_at'), 'AccountPassword', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_AccountPassword_id'), 'AccountPassword', ['id'], unique=False)
    op.create_index(op.f('ix_AccountPassword_updated_at'), 'AccountPassword', ['updated_at'], unique=False)
    op.create_table('User',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Account.id'], name='User_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index('IDX_User_username_UNIQUE', 'User', ['username'], unique=True, postgresql_where=sa.text('username IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('ix_User_created_at'), 'User', ['created_at'], unique=False)
    op.create_index(op.f('ix_User_deleted_at'), 'User', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_updated_at'), 'User', ['updated_at'], unique=False)
    op.create_table('Conversation',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('started_by_id', sa.Uuid(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['started_by_id'], ['User.id'], name='Conversations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Conversation_created_at'), 'Conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_Conversation_deleted_at'), 'Conversation', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_Conversation_id'), 'Conversation', ['id'], unique=False)
    op.create_index(op.f('ix_Conversation_last_active_at'), 'Conversation', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_Conversation_subject'), 'Conversation', ['subject'], unique=False)
    op.create_index(op.f('ix_Conversation_updated_at'), 'Conversation', ['updated_at'], unique=False)
    op.create_table('ConversationMessage',
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('human', 'robot', name='conversationmessageroleenum'), nullable=False),
    sa.Column('response_to_id', sa.Uuid(), nullable=True),
    sa.Column('response_from_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='ConversationMessages_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_from_id'], ['ConversationMessage.id'], name='ConversationMessage_response_from_id_fkey'),
    sa.ForeignKeyConstraint(['response_to_id'], ['ConversationMessage.id'], name='ConversationMessage_response_to_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_from_id'),
    sa.UniqueConstraint('response_to_id')
    )
    op.create_index(op.f('ix_ConversationMessage_created_at'), 'ConversationMessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_deleted_at'), 'ConversationMessage', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_id'), 'ConversationMessage', ['id'], unique=False)
    op.create_index(op.f('ix_ConversationMessage_updated_at'), 'ConversationMessage', ['updated_at'], unique=False)
    op.create_table('QuotedMessagesToQuotingMessagesAssocTable',
    sa.Column('quoting_id', sa.Uuid(), nullable=False),
    sa.Column('quoted_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quoted_id'], ['ConversationMessage.id'], name='ConversationMessage_quoted_id_fkey'),
    sa.ForeignKeyConstraint(['quoting_id'], ['ConversationMessage.id'], name='ConversationMessage_quoting_id_fkey'),
    sa.PrimaryKeyConstraint('quoting_id', 'quoted_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuotedMessagesToQuotingMessagesAssocTable')
    op.drop_index(op.f('ix_ConversationMessage_updated_at'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_id'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_deleted_at'), table_name='ConversationMessage')
    op.drop_index(op.f('ix_ConversationMessage_created_at'), table_name='ConversationMessage')
    op.drop_table('ConversationMessage')
    op.drop_index(op.f('ix_Conversation_updated_at'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_subject'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_last_active_at'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_id'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_deleted_at'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_created_at'), table_name='Conversation')
    op.drop_table('Conversation')
    op.drop_index(op.f('ix_User_updated_at'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_deleted_at'), table_name='User')
    op.drop_index(op.f('ix_User_created_at'), table_name='User')
    op.drop_index('IDX_User_username_UNIQUE', table_name='User', postgresql_where=sa.text('username IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('User')
    op.drop_index(op.f('ix_AccountPassword_updated_at'), table_name='AccountPassword')
    op.drop_index(op.f('ix_AccountPassword_id'), table_name='AccountPassword')
    op.drop_index(op.f('ix_AccountPassword_deleted_at'), table_name='AccountPassword')
    op.drop_index(op.f('ix_AccountPassword_created_at'), table_name='AccountPassword')
    op.drop_table('AccountPassword')
    op.drop_index(op.f('ix_AccountMeta_updated_at'), table_name='AccountMeta')
    op.drop_index(op.f('ix_AccountMeta_id'), table_name='AccountMeta')
    op.drop_index(op.f('ix_AccountMeta_deleted_at'), table_name='AccountMeta')
    op.drop_index(op.f('ix_AccountMeta_created_at'), table_name='AccountMeta')
    op.drop_index('IDX_AccountMeta_provider_provider_account_id_UNIQUE', table_name='AccountMeta', postgresql_where=sa.text("provider != 'self' AND deleted_at IS NULL"))
    op.drop_table('AccountMeta')
    op.drop_index(op.f('ix_Account_updated_at'), table_name='Account')
    op.drop_index(op.f('ix_Account_id'), table_name='Account')
    op.drop_index(op.f('ix_Account_deleted_at'), table_name='Account')
    op.drop_index(op.f('ix_Account_created_at'), table_name='Account')
    op.drop_index('IDX_Account_email_UNIQUE', table_name='Account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('Account')
    # ### end Alembic commands ###
