"""create conversation and chat message tables

Revision ID: da9ec64f4f62
Revises: 53f98e8f5f55
Create Date: 2023-08-31 17:10:02.282580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9ec64f4f62'
down_revision: Union[str, None] = '53f98e8f5f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversation',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('started_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['started_by_id'], ['User.id'], name='Conversations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Conversation_created_at'), 'Conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_Conversation_deleted_at'), 'Conversation', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_Conversation_id'), 'Conversation', ['id'], unique=False)
    op.create_index(op.f('ix_Conversation_updated_at'), 'Conversation', ['updated_at'], unique=False)
    op.create_table('ChatMessage',
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('human', 'robot', name='chatmessageroleenum'), nullable=False),
    sa.Column('response_to_id', sa.Uuid(), nullable=True),
    sa.Column('response_from_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], name='ChatMessages_conversation_id_fkey'),
    sa.ForeignKeyConstraint(['response_from_id'], ['ChatMessage.id'], name='ChatMessage_response_from_id_fkey'),
    sa.ForeignKeyConstraint(['response_to_id'], ['ChatMessage.id'], name='ChatMessage_response_to_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ChatMessage_created_at'), 'ChatMessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ChatMessage_deleted_at'), 'ChatMessage', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ChatMessage_id'), 'ChatMessage', ['id'], unique=False)
    op.create_index(op.f('ix_ChatMessage_updated_at'), 'ChatMessage', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ChatMessage_updated_at'), table_name='ChatMessage')
    op.drop_index(op.f('ix_ChatMessage_id'), table_name='ChatMessage')
    op.drop_index(op.f('ix_ChatMessage_deleted_at'), table_name='ChatMessage')
    op.drop_index(op.f('ix_ChatMessage_created_at'), table_name='ChatMessage')
    op.drop_table('ChatMessage')
    op.drop_index(op.f('ix_Conversation_updated_at'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_id'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_deleted_at'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_created_at'), table_name='Conversation')
    op.drop_table('Conversation')
    # ### end Alembic commands ###
